# A workflow that can be called from other workflows as a way to build a SNAPSHOT of Arquillian Core for testing purposes. This
# will attach an archive named "arquillian-maven-repository.tar.gz" which can be downloaded and extracted to use the
# SNAPSHOT dependencies.
#
# An output setting of "arquillian-version" is set with the version of the SNAPSHOT dependencies.
#
# Two input parameters can be set. The parameter arquillian-branch is used to control which branch you'd like a build of.
# The default branch is "main". The parameter arquillian-repo allows you to override the repository used. The default for
# this parameter is "arquillian/arquillian-core".
#
# Example Usage:
#
# jobs:
#   arquillian-build:
#     uses: arquillian/arquillian-core/.github/workflows/shared-arquillian-build.yml@main
#     with:
#       arquillian-branch: ${{ inputs.arquillian-branch }}
#       arquillian-repo: ${{ inputs.arquillian-repo }}
#
#   custom-build:
#    runs-on: ubuntu-latest
#    needs: arquillian-build
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/download-artifact@v3
#        with:
#          name: arquillian-maven-repository
#          path: .
#      - name: Extract Maven Repo
#        shell: bash
#        run: |
#          tar -xzf arquillian-maven-repository.tar.gz -C ~
#      - name: Set up JDK ${{ inputs.javaVersion }}
#        uses: actions/setup-java@v4
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: 'maven'
#      - name: Build on Linux with Java 8 using Arquillian Core ${{ needs.arquillian-build.outputs.arquillian-version }}
#        run: mvn clean verify '-Dversion.org.jboss.arquillian=${{ needs.arquillian-build.outputs.arquillian-version }}'

name: Build Arquillian Core Upstream

on:
  workflow_call:
    outputs:
      arquillian-version:
        description: "The version of Arquillian Core that was built"
        value: ${{ jobs.arquillian-build.outputs.arquillian-version }}
    inputs:
      arquillian-branch:
        description: "Arquillian Core Branch"
        required: true
        default: "main"
        type: string
      arquillian-repo:
        description: "Arquillian Core Repository"
        required: true
        default: "arquillian/arquillian-core"
        type: string

jobs:
  arquillian-build:
    runs-on: ubuntu-latest
    outputs:
      arquillian-version: ${{ steps.version.outputs.arquillian-version }}
    steps:
      - name: Checkout Arquillian Core
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.arquillian-repo }}
          ref: ${{ inputs.arquillian-branch }}
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Arquillian Core
        run: mvn clean install -DskipTests -Dcheckstyle.skip=true -Denforcer.skip=true -DskipFormatting=true
      - id: version
        run: echo "arquillian-version=$(mvn -B help:evaluate -Dexpression=project.version -DforceStdout -q)" >> $GITHUB_OUTPUT
      - name: Archive the repository
        run:  |
          cd ~
          find ./.m2/repository -type d -name "*SNAPSHOT" -print0 | xargs -0 tar -czf ~/arquillian-maven-repository.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: arquillian-maven-repository
          path: ~/arquillian-maven-repository.tar.gz
          retention-days: 5
